// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Dmu6YCYQpb5dN0dcZj8pmQYC_z2WT7Y',
    appId: '1:696908542061:web:76461bab82648eaa464f64',
    messagingSenderId: '696908542061',
    projectId: 'sashaktnirmaan-bb3f8',
    authDomain: 'sashaktnirmaan-bb3f8.firebaseapp.com',
    storageBucket: 'sashaktnirmaan-bb3f8.firebasestorage.app',
    measurementId: 'G-JVQNWJFBZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXBa8xPHn6B5Ji2i7OyuE-1J8wBcZjaWg',
    appId: '1:696908542061:android:38befe5b0669bb18464f64',
    messagingSenderId: '696908542061',
    projectId: 'sashaktnirmaan-bb3f8',
    storageBucket: 'sashaktnirmaan-bb3f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1XtjUtWCyOaEqavYWbceizDejXZjnhRM',
    appId: '1:696908542061:ios:541b981a3b41f36e464f64',
    messagingSenderId: '696908542061',
    projectId: 'sashaktnirmaan-bb3f8',
    storageBucket: 'sashaktnirmaan-bb3f8.firebasestorage.app',
    iosBundleId: 'com.sashaktnirmaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1XtjUtWCyOaEqavYWbceizDejXZjnhRM',
    appId: '1:696908542061:ios:72ea29c2b761280a464f64',
    messagingSenderId: '696908542061',
    projectId: 'sashaktnirmaan-bb3f8',
    storageBucket: 'sashaktnirmaan-bb3f8.firebasestorage.app',
    iosBundleId: 'com.example.qixerCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Dmu6YCYQpb5dN0dcZj8pmQYC_z2WT7Y',
    appId: '1:696908542061:web:b56ecd4595e0ca70464f64',
    messagingSenderId: '696908542061',
    projectId: 'sashaktnirmaan-bb3f8',
    authDomain: 'sashaktnirmaan-bb3f8.firebaseapp.com',
    storageBucket: 'sashaktnirmaan-bb3f8.firebasestorage.app',
    measurementId: 'G-GDD1QR2LM6',
  );

}