// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IJGj7PvLVRCMqaxu_jqFRBAjievNIFA',
    appId: '1:245300275518:web:87db94fdf5ec4e79ca246f',
    messagingSenderId: '245300275518',
    projectId: 'sashaktnirmaan-a8d84',
    authDomain: 'sashaktnirmaan-a8d84.firebaseapp.com',
    storageBucket: 'sashaktnirmaan-a8d84.firebasestorage.app',
    measurementId: 'G-SCMH293FD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTbqYOLvpxRXDkhyZgnmxqIo1XNFrbxI',
    appId: '1:245300275518:android:fc629a9885e80441ca246f',
    messagingSenderId: '245300275518',
    projectId: 'sashaktnirmaan-a8d84',
    storageBucket: 'sashaktnirmaan-a8d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwjV5op3BdvrBea4H3y1A_JzVTYGVdxk',
    appId: '1:245300275518:ios:64d732613206afe6ca246f',
    messagingSenderId: '245300275518',
    projectId: 'sashaktnirmaan-a8d84',
    storageBucket: 'sashaktnirmaan-a8d84.firebasestorage.app',
    iosBundleId: 'com.shashaktnirmanuserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwjV5op3BdvrBea4H3y1A_JzVTYGVdxk',
    appId: '1:245300275518:ios:056cc482b4203c12ca246f',
    messagingSenderId: '245300275518',
    projectId: 'sashaktnirmaan-a8d84',
    storageBucket: 'sashaktnirmaan-a8d84.firebasestorage.app',
    iosBundleId: 'com.example.qixerCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0IJGj7PvLVRCMqaxu_jqFRBAjievNIFA',
    appId: '1:245300275518:web:a8118bb4b20b0a9aca246f',
    messagingSenderId: '245300275518',
    projectId: 'sashaktnirmaan-a8d84',
    authDomain: 'sashaktnirmaan-a8d84.firebaseapp.com',
    storageBucket: 'sashaktnirmaan-a8d84.firebasestorage.app',
    measurementId: 'G-CK3X8E913L',
  );
}
